### PR TITLE
Delegation balance

### PR DESCRIPTION
**Pull request by sanjay-del**
Thank you for contributing to Maestro! We appreciate your effort and dedication to improving this project. To ensure that your contribution is in line with the project's guidelines and can be reviewed efficiently, please fill out the template below.

Remember to follow our [Contributing Guide](CONTRIBUTING.md) before submitting your pull request.

## Summary

Please provide a brief, concise summary of the changes in your pull request. Explain the problem you are trying to solve and the solution you have implemented.

## Type of Change

Please mark the relevant option(s) for your pull request:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring (improving code quality without changing its behavior)
- [ ] Documentation update (adding or updating documentation related to the project)

## Checklist

Please ensure that your pull request meets the following criteria:

- [x] I have read the [Contributing Guide](CONTRIBUTING.md)
- [x] My code follows the project's coding style and best practices
- [x] My code is appropriately commented and includes relevant documentation
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests pass
- [x] I have updated the documentation, if necessary

## Testing

Please describe the tests you have added or modified, and provide any additional context or instructions needed to run the tests.

- [ ] Test A
- [ ] Test B

## Additional Information

This PR closes the issue #35 (Stake account delegation history) and completes one task from issue #34 (Balance by payment credential endpoint)

### CODE REVIEW

**Comment by sanjay-del** [comment]
@Vardominator

**Comment by Vardominator** [comment]
@sanjay-del Looks good. Can you please bump the version in package.json to `1.5.4` before we merge?

**Comment by sanjay-del** [comment]
@Vardominator  updated package json version

**Review by Vardominator — APPROVED** [review]
Thank you for the contribution!!

**Comment by Vardominator** [comment]
@sanjay-del https://github.com/maestro-org/typescript-sdk/releases/tag/v1.5.4

**Pull request merged**
